'use client';

import { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, ArrowLeft, Menu, Phone, Mail, MapPin, CalendarDays, UsersRound, Clock3, Building2, SprayCan, Settings2, ShoppingCart, ShieldCheck, Package, FileText, ChevronDown, Check, X, Leaf, Wrench, ClipboardCheck, MessageCircle } from 'lucide-react';
import { Sheet, SheetTrigger, SheetContent, SheetTitle, SheetDescription, SheetClose } from '@/components/ui/sheet';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';

export type PageName = 'home'|'about'|'services'|'cases'|'contacts';
type Locale = 'ru'|'kz';
type CropName = 'aboutHero'|'servicesHero'|'caseSignature'|'residential'|'hero'|'buildingHero'|'cleaning'|'engineering'|'building'|'cart'|'quality'|'supplies'|'daily'|'deep'|'construction'|'furniture'|'historyClean'|'historyEngineer'|'historyKaz'|'historyBuilding'|'teamClean'|'teamEngineer'|'teamOffice'|'haileybury'|'kazatomprom'|'samruk';
const assets: Record<CropName, [string, number,number,number,number,number,number]> = {
  aboutHero:['about',1672,941,820,64,852,330],
  servicesHero:['services',1448,1086,710,54,738,292],
  caseSignature:['cases',1536,1024,1356,207,145,86],
  residential:['cases',1536,1024,1139,416,351,136],
  hero:['about',1672,941,795,64,870,329],
  buildingHero:['cases',1536,1024,657,70,636,234],
  cleaning:['services',1448,1086,184,397,91,171],
  engineering:['services',1448,1086,406,397,96,171],
  building:['services',1448,1086,631,397,90,171],
  cart:['services',1448,1086,853,397,93,171],
  quality:['services',1448,1086,1077,397,88,171],
  supplies:['services',1448,1086,1304,397,85,171],
  daily:['services',1448,1086,390,635,231,81],
  deep:['services',1448,1086,641,635,234,81],
  construction:['services',1448,1086,896,635,235,81],
  furniture:['services',1448,1086,1152,635,234,81],
  historyClean:['about',1672,941,56,454,128,125],
  historyEngineer:['about',1672,941,448,454,123,124],
  historyKaz:['about',1672,941,845,454,128,124],
  historyBuilding:['about',1672,941,1253,454,124,124],
  teamClean:['about',1672,941,1059,619,139,189],
  teamEngineer:['about',1672,941,1205,619,206,189],
  teamOffice:['about',1672,941,1428,619,188,189],
  haileybury:['cases',1536,1024,50,412,348,139],
  kazatomprom:['cases',1536,1024,413,412,348,139],
  samruk:['cases',1536,1024,778,412,346,139],
};
function Photo({name, className='', alt=''}:{name:CropName;className?:string;alt?:string}) {
  const [file,width,height,x,y,w,h]=assets[name];
  return <svg className={`photo ${className}`} viewBox={`${x} ${y} ${w} ${h}`} preserveAspectRatio="xMidYMid slice" role={alt?'img':undefined} aria-label={alt||undefined} aria-hidden={alt?undefined:true}><image href={`/images/${file}-reference.png`} width={width} height={height}/></svg>;
}
function Eyebrow({children,light=false}:{children:React.ReactNode;light?:boolean}) { return <p className={`eyebrow ${light?'light':''}`}><span/>{children}</p>; }
function Arrow({circle=false}:{circle?:boolean}) {return circle?<span className="circle-arrow"><ArrowRight size={18}/></span>:<ArrowRight size={18} aria-hidden="true"/>;}

export default function Site({page,locale}:{page:PageName;locale:Locale}) {
  const t=(ru:string,kz:string)=>locale==='ru'?ru:kz;
  const path=(p:PageName)=>`${locale==='kz'?'/kz':''}${p==='home'?(locale==='ru'?'/':''):`/${p}`}`;
  const whatsapp=`https://wa.me/77012200112?text=${encodeURIComponent(t('Здравствуйте! Хочу обсудить обслуживание объекта с AAA service.','Сәлеметсіз бе! AAA service компаниясымен нысанға қызмет көрсетуді талқылағым келеді.'))}`;
  const [menuOpen,setMenuOpen]=useState(false);
  const [caseFilter,setCaseFilter]=useState('all');
  const [caseOffset,setCaseOffset]=useState(0);
  const [selectedCase,setSelectedCase]=useState<number|null>(null);
  const [serviceTab,setServiceTab]=useState('cleaning');
  const nav:{id:PageName;name:string}[]=[{id:'home',name:t('Главная','Басты бет')},{id:'about',name:page==='cases'?t('О компании','Компания туралы'):t('О нас','Біз туралы')},{id:'services',name:t('Услуги','Қызметтер')},{id:'cases',name:t('Кейсы','Жобалар')},{id:'contacts',name:t('Контакты','Байланыс')}];
  const services=[
    {id:'cleaning',title:t('Профессиональная уборка','Кәсіби тазалау'),desc:t('Ежедневный и специализированный клининг любой сложности.','Күнделікті және кез келген күрделіліктегі арнайы клининг.'),icon:SprayCan,photo:'cleaning' as CropName},
    {id:'engineering',title:t('Инженерное сопровождение','Инженерлік қолдау'),desc:t('Техническая эксплуатация и обслуживание инженерных систем.','Инженерлік жүйелерді пайдалану және техникалық қызмет көрсету.'),icon:Settings2,photo:'engineering' as CropName},
    {id:'management',title:t('Комплексное управление','Кешенді басқару'),desc:t('Единый оператор всех сервисов на объекте.','Нысандағы барлық қызметке жауапты бір оператор.'),icon:Building2,photo:'building' as CropName},
    {id:'household',title:t('Хозяйственный сервис','Шаруашылық қызмет'),desc:t('Вспомогательные услуги для комфортной работы объекта.','Нысанның жайлы жұмысына арналған қосымша қызметтер.'),icon:ShoppingCart,photo:'cart' as CropName},
    {id:'quality',title:t('Контроль качества','Сапаны бақылау'),desc:t('Регулярные проверки и стандарты обслуживания.','Тұрақты тексерістер мен бірыңғай қызмет стандарттары.'),icon:ShieldCheck,photo:'quality' as CropName},
    {id:'supplies',title:t('Снабжение и расходные материалы','Жабдықтау және материалдар'),desc:t('Поставка расходных материалов и инвентаря для бесперебойной работы.','Үздіксіз жұмыс үшін қажетті материалдар мен жабдықтар.'),icon:Package,photo:'supplies' as CropName},
  ];
  const history=[
    {year:'2007',title:t('Начало деятельности','Қызметтің басталуы'),desc:t('Стартовали с хозяйственного аутсорсинга, сформировав основу нашей экспертизы.','Шаруашылық аутсорсингтен бастап, кәсіби тәжірибеміздің негізін қаладық.'),photo:'historyClean' as CropName},
    {year:'2011',title:t('Комплексное обслуживание зданий','Ғимараттарға кешенді қызмет'),desc:t('Расширили спектр услуг и начали комплексное обслуживание объектов.','Қызмет аясын кеңейтіп, нысандарға кешенді қызмет көрсете бастадық.'),photo:'historyEngineer' as CropName},
    {year:'2018',title:t('Казатомпром','Қазатомөнеркәсіп'),desc:t('Стали партнёром Казатомпром, укрепив позиции на рынке крупных объектов.','Қазатомөнеркәсіптің серіктесі болып, ірі нысандар нарығындағы орнымызды нығайттық.'),photo:'historyKaz' as CropName},
    {year:'2026',title:t('Расширение направлений группы','Топтың дамуы'),desc:t('Продолжаем развиваться, расширяя направления и географию присутствия.','Қызмет бағыттары мен географиямызды кеңейтіп, дамуды жалғастырамыз.'),photo:'historyBuilding' as CropName},
  ];
  const cases=[
    {name:'Haileybury Astana',category:'education',label:t('Образование','Білім беру'),date:'2011 — 2013',photo:'haileybury' as CropName,city:t('Астана','Астана'),desc:t('Комплексное обслуживание здания и прилегающей территории международной английской школы.','Халықаралық ағылшын мектебінің ғимараты мен аумағына кешенді қызмет көрсету.'),details:t('AAA service выступала генеральным подрядчиком по комплексному обслуживанию школы в 2011–2013 годах. В задачи входила работа с инженерными коммуникациями, уборка помещений и обслуживание прилегающей территории.','AAA service 2011–2013 жылдары мектепке кешенді қызмет көрсететін бас мердігер болды. Жұмысқа инженерлік жүйелерге қызмет көрсету, үй-жайлар мен іргелес аумақты тазалау кірді.')},
    {name:t('АО «Казатомпром»','«Қазатомөнеркәсіп» АҚ'),category:'state',label:t('Государственный сектор','Мемлекеттік сектор'),date:t('с 2018 — по настоящее время','2018 жылдан бүгінге дейін'),photo:'kazatomprom' as CropName,city:t('Астана','Астана'),desc:t('Генеральный подрядчик по комплексному обслуживанию здания головного офиса. Сотрудничаем более 8 лет.','Бас кеңсе ғимаратына кешенді қызмет көрсететін бас мердігер. 8 жылдан астам ынтымақтастық.'),details:t('С 2018 года обслуживаем здание головного офиса АО «Национальная атомная компания «Казатомпром» в Астане. Многолетнее сотрудничество объединяет техническую эксплуатацию и ежедневный сервис на объекте.','2018 жылдан бері Астанадағы «Қазатомөнеркәсіп» ұлттық атом компаниясының бас кеңсесіне қызмет көрсетеміз. Ұзақ мерзімді серіктестік техникалық пайдалану мен күнделікті сервисті біріктіреді.')},
    {name:t('АО «ФНБ «Самрук-Казына»','«Самұрық-Қазына» ҰӘҚ» АҚ'),category:'state',label:t('Государственный сектор','Мемлекеттік сектор'),date:'2020',photo:'samruk' as CropName,city:t('Астана','Астана'),desc:t('Победа в конкурсе на годовое обслуживание противопожарных систем здания головного офиса.','Бас кеңсе ғимаратының өртке қарсы жүйелеріне жылдық қызмет көрсету.'),details:t('В 2020 году AAA service стала генеральным подрядчиком по результатам конкурса на годовое обслуживание противопожарных систем головного офиса АО «ФНБ «Самрук-Казына».','2020 жылы AAA service «Самұрық-Қазына» ҰӘҚ» АҚ бас кеңсесінің өртке қарсы жүйелеріне жылдық қызмет көрсету байқауының қорытындысы бойынша бас мердігер болды.')},
    {name:t('Современные жилые комплексы','Заманауи тұрғын үй кешендері'),category:'residential',label:t('Жилые комплексы','Тұрғын үй кешендері'),date:'2024 — 2026',photo:'residential' as CropName,city:t('Астана / Алматы','Астана / Алматы'),desc:t('Комплексное управление и эксплуатация жилых комплексов: инженерные системы, клининг, сервис и благоустройство.','Тұрғын үй кешендерін кешенді басқару және пайдалану: инженерлік жүйелер, клининг, сервис және абаттандыру.'),details:t('Комплексное управление и эксплуатация жилых комплексов: инженерные системы, клининг, сервис и благоустройство. Астана / Алматы, 2024–2026.','Тұрғын үй кешендерін кешенді басқару және пайдалану: инженерлік жүйелер, клининг, сервис және абаттандыру. Астана / Алматы, 2024–2026.')},
  ];
  const steps=[
    [t('Обследование','Тексеру'),t('Анализируем объект и задачи.','Нысан мен міндеттерді талдаймыз.')],
    [t('Регламент','Регламент'),t('Разрабатываем модель обслуживания.','Қызмет көрсету моделін әзірлейміз.')],
    [t('Работа','Жұмыс'),t('Формируем команду и запускаем сервис.','Команданы құрып, жұмысты бастаймыз.')],
    [t('Контроль','Бақылау'),t('Проверяем качество и улучшаем сервис.','Сапаны тексеріп, сервисті жақсартамыз.')],
  ];

  useEffect(()=>{
    document.documentElement.lang=locale==='kz'?'kk':'ru';
    setMenuOpen(false);
    const hash=window.location.hash.slice(1);
    if(['cleaning','engineering','management'].includes(hash)) setServiceTab(hash);
    const elements=document.querySelectorAll('.reveal');
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:0.07});
    elements.forEach(el=>observer.observe(el));
    const updateTab=()=>{const h=window.location.hash.slice(1); if(['cleaning','engineering','management'].includes(h))setServiceTab(h);};
    window.addEventListener('hashchange',updateTab);
    return ()=>{observer.disconnect();window.removeEventListener('hashchange',updateTab);};
  },[page,locale]);

  const RequestButton=({label,outline=false}:{label?:string;outline?:boolean})=><a className={`button ${outline?'secondary-button':''}`} href={whatsapp} target="_blank" rel="noopener noreferrer">{label||t('Оставить заявку','Өтінім қалдыру')}<Arrow/></a>;
  const Stats=({compact=false,area=false}:{compact?:boolean;area?:boolean})=><div className={`stats ${compact?'compact':''}`}>
    {[{icon:CalendarDays,value:t('с 2007','2007 жылдан'),label:t('на рынке','нарықта')},{icon:UsersRound,value:'100+',label:t('специалистов','маман')},{icon:Clock3,value:'24/7',label:t('сопровождение','қолдау')},area?{icon:Building2,value:'420 000+ м²',label:t('обслуживаемая площадь','қызмет көрсетілетін аумақ')}:{icon:ShieldCheck,value:t('Единый','Бірыңғай'),label:t('стандарт качества','сапа стандарты')}].map(({icon:Icon,value,label})=><div className="stat" key={label}><Icon/><div><strong>{value}</strong><span>{label}</span></div></div>)}
  </div>;
  const SectionHeading=({eyebrow,title,link,label}:{eyebrow:string;title:string;link?:PageName;label?:string})=><div className="section-heading"><div><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2></div>{link&&<a className="text-link" href={path(link)}>{label||t('Подробнее','Толығырақ')}<Arrow circle/></a>}</div>;
  const ServiceCards=({all=false}:{all?:boolean})=><div className={`service-grid ${all?'six':''}`}>{services.slice(0,all?6:5).map(({id,title,desc,icon:Icon,photo})=><article className="service-card" key={id}><div className="service-copy"><Icon className="service-icon"/><h3>{title}</h3><p>{desc}</p><a href={`${path('services')}#${['household','quality','supplies'].includes(id)?'management':id}`} onClick={()=>setServiceTab(['household','quality','supplies'].includes(id)?'management':id)} className="service-action" aria-label={`${t('Подробнее:','Толығырақ:')} ${title}`}><Arrow circle/></a></div><Photo name={photo}/></article>)}</div>;
  const Timeline=({full=false}:{full?:boolean})=><div className={`timeline ${full?'full':''}`}>{history.map(item=><article className="timeline-item" key={item.year}><i/><Photo name={item.photo}/><div><strong>{item.year}</strong><h3>{item.title}</h3>{full&&<p>{item.desc}</p>}</div></article>)}</div>;
  const Process=()=> <section className="section container reveal process-section"><SectionHeading eyebrow={t('Как мы работаем','Қалай жұмыс істейміз')} title={t('Простой и прозрачный процесс','Қарапайым әрі ашық үдеріс')}/><div className="process-grid">{steps.map(([title,desc],i)=><article key={title}><span className="step-number">{i+1}</span><div><h3>{title}</h3><p>{desc}</p></div>{i<3&&<ArrowRight className="step-arrow"/>}</article>)}</div></section>;
  const Banner=({red=false}:{red?:boolean})=>red?<section className="cta-banner red reveal"><Photo name="buildingHero"/><div className="cta-copy"><Eyebrow light>{t('Готовы к сотрудничеству?','Ынтымақтастыққа дайынсыз ба?')}</Eyebrow><h2>{t('Давайте обсудим ваш объект','Нысаныңызды талқылайық')}</h2></div><p className="audit-description">{t('Проведём аудит, предложим оптимальное решение и создадим комфортную среду вместе.','Аудит жүргізіп, оңтайлы шешім ұсынамыз және бірге жайлы орта құрамыз.')}</p><RequestButton label={t('Получить бесплатный аудит','Тегін аудит алу')}/></section>:<section className="cta-banner reveal"><Photo name="hero"/><div className="cta-copy"><h2>{t('Обсудим ваш объект','Нысаныңызды талқылайық')}</h2><p>{page==='about'||page==='services'?t('Подберём состав услуг, модель обслуживания и рассчитаем стоимость.','Қызметтерді, қызмет көрсету моделін таңдап, құнын есептейміз.'):t('Подберём состав услуг, модель обслуживания и график работ под ваши задачи.','Міндеттеріңізге сәйкес қызметтерді, қызмет көрсету моделін және жұмыс кестесін таңдаймыз.')}</p></div><div className="cta-actions"><RequestButton label={page==='services'?t('Оставить заявку','Өтінім қалдыру'):t('Обсудить объект','Нысанды талқылау')}/><a className="button secondary-button" href={page==='about'?whatsapp:path('contacts')} target={page==='about'?'_blank':undefined} rel={page==='about'?'noopener noreferrer':undefined}>{page==='about'?t('Получить предложение','Ұсыныс алу'):t('Связаться с нами','Бізбен байланысу')}<Arrow/></a></div>{(page==='about'||page==='services')&&<p className="banner-motto">{t('Сервис\nсоздаёт\nкомфорт','Сервис\nжайлылық\nжасайды')}</p>}</section>;
  const CaseCards=({small=false,filter='all'}:{small?:boolean;filter?:string})=>{
    const items=(small?cases.slice(0,3):cases).map((item,index)=>({item,index})).filter(({item})=>filter==='all'||item.category===filter);
    const ordered=small?items:items.map((_,index)=>items[(index+caseOffset)%items.length]);
    return items.length?<div className={`case-grid ${small?'small':''}`} data-testid="case-grid">{ordered.map(({item,index})=><article className="case-card" key={item.name}><div className="case-image"><Photo name={item.photo} alt={item.name}/>{!small&&<span className="case-label">{item.label}</span>}</div><div className="case-body"><h3>{item.name}</h3><p>{item.desc}</p>{!small&&<div className="case-meta"><span><CalendarDays/>{item.date}</span><span><MapPin/>{item.city}</span></div>}<button type="button" className="case-open" aria-label={`${t('Открыть кейс','Жобаны ашу')}: ${item.name}`} onClick={()=>setSelectedCase(index)}><Arrow circle/></button></div></article>)}</div>:<Empty className="case-empty"><EmptyHeader><EmptyTitle>{t('Кейсы появятся здесь','Жобалар осында пайда болады')}</EmptyTitle><EmptyDescription>{t('В этой категории пока нет опубликованных кейсов. Посмотрите наши другие объекты.','Бұл санатта әзірге жарияланған жобалар жоқ. Басқа нысандарымызды қараңыз.')}</EmptyDescription></EmptyHeader><button className="button secondary-button" onClick={()=>setCaseFilter('all')}>{t('Все кейсы','Барлық жобалар')}<Arrow/></button></Empty>;
  };

  function Hero() {
    const content={
      home:{eyebrow:t('Профессиональный сервис для вашего бизнеса','Бизнесіңізге арналған кәсіби сервис'),title:<>{t('Больше, чем клининг.','Клинингтен де артық.')}<br/>{t('Мы управляем комфортом','Біз жайлылықты басқарамыз')}</>,desc:t('Клининг, инженерные системы и ежедневная эксплуатация объекта — в одной сервисной модели.','Клининг, инженерлік жүйелер және нысанды күнделікті пайдалану — біртұтас қызмет көрсету моделінде.')},
      about:{eyebrow:t('О компании','Компания туралы'),title:<>{t('Сервисная компания','2007 жылдан бері')}<br/>{t('с опытом с 2007 года','қызмет көрсететін компания')}</>,desc:t('AAA SERVICE начинала свою деятельность с хозяйственного аутсорсинга, а сегодня предоставляет полный спектр услуг: клининг, инженерные системы, хозяйственные процессы и комплексное обслуживание недвижимости.','AAA SERVICE өз жұмысын шаруашылық аутсорсингтен бастады. Бүгінде клининг, инженерлік жүйелер, шаруашылық үдерістер және жылжымайтын мүлікке кешенді қызмет көрсетуді ұсынады.')},
      services:{eyebrow:t('Наши услуги','Біздің қызметтер'),title:<>{t('Комплексный сервис','Заманауи нысандарға')}<br/>{t('для современных объектов','кешенді қызмет')}</>,desc:t('Клининг, инженерные системы, хозяйственные процессы и комплексное обслуживание в единой сервисной модели.','Клининг, инженерлік жүйелер, шаруашылық үдерістер және кешенді қызмет — біртұтас модельде.')},
      cases:{eyebrow:t('Наши кейсы','Біздің жобалар'),title:<>{t('Нам доверяют','Бізге маңызды')}<br/>{t('важные ','')}<em>{t('объекты','нысандар сенеді')}</em></>,desc:t('Мы создаём комфортную и безопасную среду для людей, чтобы они могли сосредоточиться на главном.','Адамдар басты істеріне көңіл бөлуі үшін жайлы әрі қауіпсіз орта жасаймыз.')},
      contacts:{eyebrow:t('Контакты','Байланыс'),title:<>{t('Хороший сервис','Жақсы сервис')}<br/>{t('начинается с ','')}<em>{t('диалога','диалогтан басталады')}</em></>,desc:t('Расскажите о вашем объекте. Вместе определим задачи и подберём подходящий формат обслуживания.','Нысаныңыз туралы айтып беріңіз. Міндеттерді бірге анықтап, қолайлы қызмет көрсету форматын таңдаймыз.')},
    };
    const c=content[page];
    return <section className={`hero hero-${page}`}><div className="hero-art"><Photo name={page==='cases'?'buildingHero':page==='about'?'aboutHero':page==='services'?'servicesHero':'hero'}/></div><div className="hero-veil"/><div className="container hero-inner">{page==='cases'&&<aside className="cases-hero-note"><p>{t('Чистые пространства\nБольшие возможности','Таза кеңістік\nҮлкен мүмкіндіктер')}</p>{locale==='ru'?<Photo name="caseSignature" alt="Вместе к лучшему"/>:<em>Жақсылыққа бірге</em>}</aside>}<div className="hero-copy"><Eyebrow>{c.eyebrow}</Eyebrow><h1>{c.title}</h1><p className="hero-description">{c.desc}</p>{['home','services','contacts'].includes(page)&&<div className="hero-actions"><RequestButton/>{page==='home'?<a href={path('about')} className="button secondary-button">{t('О компании','Компания туралы')}<Arrow/></a>:<a href="tel:+77012200112" className="button secondary-button">{t('Получить консультацию','Кеңес алу')}<Arrow/></a>}</div>}{page==='home'&&<div className="hero-benefits">{[{icon:SprayCan,text:t('Клининг\nи эксплуатация','Клининг және\nпайдалану')},{icon:Settings2,text:t('Инженерные\nсистемы','Инженерлік\nжүйелер')},{icon:UsersRound,text:t('Комплексное\nуправление','Кешенді\nбасқару')}].map(({icon:Icon,text})=><div key={text}><span><Icon/></span><p>{text}</p></div>)}</div>}{['about','services'].includes(page)&&<Stats compact area/>}</div>{page==='home'&&<div className="hero-proof"><div><b>{t('с 2007','2007 жылдан')}</b><span>{t('на рынке','нарықта')}</span></div><div><b>100+</b><span>{t('специалистов','маман')}</span></div><div><b>24/7</b><span>{t('сопровождение','қолдау')}</span></div></div>}</div></section>;
  }

  function HomeContent() {return <>
    <section className="section container reveal"><SectionHeading eyebrow={t('Наши услуги','Біздің қызметтер')} title={t('Комплексный сервис для современных объектов','Заманауи нысандарға кешенді қызмет')} link="services" label={t('Все услуги','Барлық қызметтер')}/><ServiceCards/></section>
    <section className="section container home-about reveal"><div><Eyebrow>{t('О компании','Компания туралы')}</Eyebrow><h2>{t('Сервисная компания','2007 жылдан бері')}<br/>{t('с опытом с 2007 года','қызмет көрсететін компания')}</h2><p>{t('AAA service развивает комплексное обслуживание недвижимости: клининг, инженерные системы, хозяйственные и эксплуатационные процессы. Мы последовательно расширяем компетенции вокруг потребностей объектов.','AAA service жылжымайтын мүлікке кешенді қызмет көрсетуді дамытады: клининг, инженерлік жүйелер, шаруашылық және пайдалану үдерістері. Нысандардың қажеттіліктеріне сай құзыретімізді кеңейтеміз.')}</p><a href={path('about')} className="button secondary-button small-button">{t('Подробнее о компании','Компания туралы толығырақ')}<Arrow/></a></div><div className="home-history"><h3 className="minor-title">{t('История развития','Даму тарихы')}</h3><Timeline/></div></section>
    <section className="ecosystem-section reveal"><div className="container ecosystem"><div className="ecosystem-intro"><Eyebrow>{t('Как формировалась AAA service','AAA service қалай қалыптасты')}</Eyebrow><h2>{t('Сильная сервисная экосистема','Мықты сервистік экожүйе')}</h2><p>{t('Мы последовательно развивали компетенции, чтобы предлагать полный спектр услуг для ваших объектов.','Нысандарыңызға қызметтің толық ауқымын ұсыну үшін құзыретімізді кезең-кезеңімен дамыттық.')}</p></div><div className="ecosystem-cards">{[{image:'supplies',title:t('Хозяйственный аутсорсинг','Шаруашылық аутсорсинг'),desc:t('Старт и базовые услуги','Бастапқы және негізгі қызметтер')},{image:'daily',title:t('Клининг и ежедневный сервис','Клининг және күнделікті сервис'),desc:t('Чистые и безопасные пространства','Таза және қауіпсіз кеңістік')},{image:'historyEngineer',title:t('Инженерное сопровождение','Инженерлік қолдау'),desc:t('Надёжная работа систем','Жүйелердің сенімді жұмысы')},{image:'historyBuilding',title:t('Комплексное обслуживание','Кешенді қызмет көрсету'),desc:t('Единые стандарты и ответственность','Бірыңғай стандарттар мен жауапкершілік')}].map((x,i)=><article key={x.title}><Photo name={x.image as CropName}/><h3>{x.title}</h3><p>{x.desc}</p>{i<3&&<ArrowRight className="ecosystem-arrow"/>}</article>)}</div></div></section>
    <section className="section container case-stats-section reveal"><div><SectionHeading eyebrow={t('Наши кейсы','Біздің жобалар')} title={t('Реальные объекты. Доверие клиентов.','Нақты нысандар. Клиенттер сенімі.')} link="cases" label={t('Все кейсы','Барлық жобалар')}/><CaseCards small/></div><div><SectionHeading eyebrow={t('Наши показатели','Біздің көрсеткіштер')} title={t('Мы в цифрах','Біз сандармен')}/><Stats/></div></section>
    <Process/>
  </>;}

  function AboutContent() {return <>
    <section className="section container reveal history-section"><h2 className="line-heading">{t('История развития','Даму тарихы')}</h2><Timeline full/></section>
    <section className="team-section reveal"><div className="container team-layout"><div className="team-intro"><Eyebrow>{t('Наша команда','Біздің команда')}</Eyebrow><h2>{t('На вас работает не только персонал на объекте','Сіз үшін тек нысандағы қызметкерлер ғана жұмыс істемейді')}</h2><p>{t('За каждым проектом стоит сильная команда в офисе. Мы обеспечиваем бесперебойную работу благодаря профессионалам в ключевых направлениях: снабжение, юридическое сопровождение, отдел кадров и подбора персонала, бухгалтерский учёт, экономика и финансы.','Әр жобаның артында кеңседегі мықты команда тұр. Жабдықтау, құқықтық сүйемелдеу, кадрларды іріктеу, бухгалтерлік есеп, экономика және қаржы мамандары үздіксіз жұмысты қамтамасыз етеді.')}</p></div><div className="department-grid">{[{icon:ShoppingCart,title:t('Снабжение','Жабдықтау'),desc:t('Надёжные поставки и контроль качества','Сенімді жеткізу және сапаны бақылау')},{icon:FileText,title:t('Юридическое сопровождение','Құқықтық сүйемелдеу'),desc:t('Правовая поддержка и безопасность','Құқықтық қолдау және қауіпсіздік')},{icon:UsersRound,title:t('Отдел кадров и подбора персонала','Кадрлар және мамандарды іріктеу бөлімі'),desc:t('Профессиональная команда','Кәсіби команда')},{icon:Building2,title:t('Бухгалтерский учёт, экономика и финансы','Бухгалтерлік есеп, экономика және қаржы'),desc:t('Прозрачность и эффективность','Ашықтық және тиімділік')}].map(({icon:Icon,title,desc})=><article key={title}><Icon/><h3>{title}</h3><p>{desc}</p></article>)}</div><div className="team-photos"><Photo name="teamClean"/><Photo name="teamEngineer"/><Photo name="teamOffice"/></div></div></section>
  </>;}

  const detailGroups=[
    {id:'cleaning',title:t('Клининг','Клининг'),description:t('Чистота, комфорт и безопасная среда для ваших сотрудников и гостей.','Қызметкерлеріңіз бен қонақтарыңыз үшін тазалық, жайлылық және қауіпсіз орта.'),icon:SprayCan,items:[{photo:'daily',title:t('Ежедневная уборка','Күнделікті тазалау'),text:t('Поддержание чистоты и порядка на объекте.','Нысанда тазалық пен тәртіпті сақтау.')},{photo:'deep',title:t('Генеральная уборка','Жалпы тазалау'),text:t('Комплексная очистка всех зон.','Барлық аймақтарды кешенді тазалау.')},{photo:'construction',title:t('Послестроительный клининг','Құрылыстан кейінгі клининг'),text:t('Подготовка объекта к эксплуатации.','Нысанды пайдалануға дайындау.')},{photo:'furniture',title:t('Химчистка','Химиялық тазалау'),text:t('Профессиональная чистка мебели, ковров и текстиля.','Жиһаз, кілем және тоқыма бұйымдарын кәсіби тазалау.')}]},
    {id:'engineering',title:t('Инженерные системы','Инженерлік жүйелер'),description:t('Техническая эксплуатация, диагностика и плановое обслуживание коммуникаций.','Инженерлік жүйелерді техникалық пайдалану, диагностика және жоспарлы қызмет көрсету.'),icon:Settings2,items:[{photo:'historyEngineer',title:t('Электроснабжение','Электрмен жабдықтау'),text:t('Электрооборудование и распределительные щиты.','Электр жабдықтары мен тарату қалқандары.')},{photo:'teamEngineer',title:t('Вентиляция и климат','Желдету және климат'),text:t('Вентиляция, кондиционирование и отопление.','Желдету, ауа баптау және жылыту.')},{photo:'engineering',title:t('Вода и канализация','Су және кәріз'),text:t('Обслуживание водоснабжения и водоотведения.','Сумен жабдықтау және су бұру жүйелері.')},{photo:'quality',title:t('Системы безопасности','Қауіпсіздік жүйелері'),text:t('Противопожарные системы, СКУД и видеонаблюдение.','Өртке қарсы жүйелер, кіруді бақылау және бейнебақылау.')}]},
    {id:'management',title:t('Комплексное управление','Кешенді басқару'),description:t('Все задачи по эксплуатации недвижимости — в одной системе ответственности.','Жылжымайтын мүлікті пайдалану міндеттері — бірыңғай жауапкершілік жүйесінде.'),icon:Building2,items:[{photo:'cart',title:t('Хозяйственный сервис','Шаруашылық қызмет'),text:t('Ежедневная поддержка работы объекта.','Нысан жұмысын күнделікті қолдау.')},{photo:'supplies',title:t('Снабжение','Жабдықтау'),text:t('Материалы, инвентарь и контроль поставок.','Материалдар, жабдықтар және жеткізуді бақылау.')},{photo:'historyBuilding',title:t('Уход за территорией','Аумақты күтіп ұстау'),text:t('Уборка, озеленение и сезонные работы.','Тазалау, көгалдандыру және маусымдық жұмыстар.')},{photo:'quality',title:t('Контроль и отчётность','Бақылау және есеп'),text:t('Проверка качества и прозрачность процессов.','Сапаны тексеру және үдерістердің ашықтығы.')}]},
  ];
  function ServicesContent() {return <>
    <section className="section container reveal service-directions" id="all-services"><div className="reference-section-heading"><h2 className="line-heading stacked">{t('Основные направления услуг','Негізгі қызмет бағыттары')}</h2><a className="text-link" href="#all-services">{t('Все услуги','Барлық қызметтер')}<Arrow circle/></a></div><ServiceCards all/></section>
    <section className="section container reveal detail-section" id="service-details"><span className="anchor-target" id="cleaning"/><span className="anchor-target" id="engineering"/><span className="anchor-target" id="management"/><Tabs value={serviceTab} onValueChange={setServiceTab}><div className="detail-heading"><h2 className="line-heading stacked">{t('Детализация услуг','Қызметтер туралы толығырақ')}</h2><TabsList variant="line" className="service-tabs">{detailGroups.map(g=><TabsTrigger value={g.id} key={g.id}>{g.title}</TabsTrigger>)}</TabsList></div>{detailGroups.map(g=><TabsContent key={g.id} value={g.id} className="service-detail"><div className="detail-intro"><g.icon/><h3>{g.title}</h3><p>{g.description}</p><RequestButton label={t('Подробнее об услуге','Қызмет туралы толығырақ')} outline/></div><div className="detail-cards">{g.items.map(item=><article key={item.title}><Photo name={item.photo as CropName}/><div><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></TabsContent>)}</Tabs></section>
    <section className="container reference-process reveal"><h2 className="line-heading stacked">{t('Как мы подключаем сервис','Сервисті қалай қосамыз')}</h2><div className="process-grid">{[[t('Обследование','Тексеру'),t('Анализируем объект и задачи.','Нысан мен міндеттерді талдаймыз.')],[t('Регламент','Регламент'),t('Разрабатываем модель обслуживания.','Қызмет көрсету моделін әзірлейміз.')],[t('Запуск','Іске қосу'),t('Формируем команду и начинаем работу.','Команданы құрып, жұмысты бастаймыз.')],[t('Контроль','Бақылау'),t('Постоянный мониторинг и улучшение сервиса.','Тұрақты бақылау және сервисті жетілдіру.')]].map(([title,desc],i)=><article key={title}><span className="step-number">{i+1}</span><div><h3>{title}</h3><p>{desc}</p></div>{i<3&&<ArrowRight className="step-arrow"/>}</article>)}</div></section>
    <section className="container reference-advantages reveal"><h2 className="line-heading">{t('Наши преимущества','Біздің артықшылықтар')}</h2><div className="advantages-grid">{[{icon:Clock3,title:'24/7',label:t('сопровождение','қолдау'),description:t('Оперативное решение любых задач','Кез келген міндетті жедел шешу')},{icon:UsersRound,title:'100+',label:t('специалистов','маман'),description:t('Опытная команда на вашем объекте','Нысаныңыздағы тәжірибелі команда')},{icon:CalendarDays,title:t('с 2007 года','2007 жылдан'),label:t('на рынке','нарықта'),description:t('Надёжный партнёр с проверенной репутацией','Беделі дәлелденген сенімді серіктес')},{icon:ShieldCheck,title:t('Единый стандарт качества','Бірыңғай сапа стандарты'),label:'',description:t('Прозрачные процессы и ответственность','Ашық үдерістер және жауапкершілік')}].map(({icon:Icon,title,label,description})=><article key={title}><Icon/><div><strong>{title}</strong>{label&&<span>{label}</span>}</div><p>{description}</p></article>)}</div></section>
  </>;}

  function CasesContent() {
    const categories=[['all',t('Все кейсы','Барлық жобалар')],['business',t('Бизнес-центры','Бизнес-орталықтар')],['state',t('Государственные объекты','Мемлекеттік нысандар')],['education',t('Образование','Білім беру')],['commercial',t('Коммерческая недвижимость','Коммерциялық жылжымайтын мүлік')],['residential',t('Жилые комплексы','Тұрғын үй кешендері')]];
    const count=cases.filter(item=>caseFilter==='all'||item.category===caseFilter).length;
    return <><section className="section container reveal cases-section"><div className="case-toolbar"><div className="case-filters" aria-label={t('Категории кейсов','Жоба санаттары')}>{categories.map(([id,label])=><button key={id} className={caseFilter===id?'active':''} aria-pressed={caseFilter===id} onClick={()=>{setCaseFilter(id);setCaseOffset(0);}}>{label}</button>)}</div><div className="case-carousel-controls"><button className="circle-arrow" aria-label={t('Предыдущие кейсы','Алдыңғы жобалар')} disabled={count<2} onClick={()=>setCaseOffset(v=>(v+count-1)%count)}><ArrowLeft size={16}/></button><button className="circle-arrow" aria-label={t('Следующие кейсы','Келесі жобалар')} disabled={count<2} onClick={()=>setCaseOffset(v=>(v+1)%count)}><ArrowRight size={16}/></button></div></div><div aria-live="polite"><CaseCards filter={caseFilter}/></div></section><section className="container trust-section reveal"><div className="trust-metrics"><Eyebrow>{t('Нам доверяют','Бізге сенеді')}</Eyebrow><div className="trust-numbers"><div><strong>15+</strong><span>{t('лет на рынке','нарықтағы жыл')}</span></div><div><strong>100+</strong><span>{t('профессионалов в команде','командадағы маман')}</span></div><div><strong>50+</strong><span>{t('объектов в управлении','басқарудағы нысан')}</span></div><div><strong>{t('1.5+ млн м²','1.5+ млн м²')}</strong><span>{t('общая площадь','жалпы аумақ')}</span></div></div></div><div className="trust-quote"><span>“</span><blockquote><p>{t('«Профессионализм команды AAA Service позволяет нам быть уверенными в безопасности, комфорте и бесперебойной работе нашего объекта.»','«AAA Service командасының кәсібилігі нысанымыздың қауіпсіздігіне, жайлылығына және үздіксіз жұмысына сенімді болуға мүмкіндік береді.»')}</p><cite><i/>{t('АО «Казатомпром»','«Қазатомөнеркәсіп» АҚ')}</cite></blockquote><div className="quote-actions"><button className="circle-arrow" aria-label={t('Посмотреть кейс Казатомпрома','Қазатомөнеркәсіп жобасын қарау')} onClick={()=>setSelectedCase(1)}><ArrowRight size={16}/></button><a className="circle-arrow" href={whatsapp} target="_blank" rel="noopener noreferrer" aria-label={t('Обсудить объект','Нысанды талқылау')}><ArrowRight size={16}/></a></div></div></section></>;
  }

  function ContactsContent() {return <section className="section container contact-layout reveal"><div><SectionHeading eyebrow={t('Всегда на связи','Әрдайым байланыстамыз')} title={t('Давайте познакомимся','Танысайық')}/><div className="contact-cards"><a href="tel:+77012200112"><Phone/><div><span>{t('Телефон','Телефон')}</span><strong>+7 701 220 01 12</strong></div><ArrowUpRight/></a><a href="mailto:info@aaaservice.kz"><Mail/><div><span>{t('Электронная почта','Электрондық пошта')}</span><strong>info@aaaservice.kz</strong></div><ArrowUpRight/></a><a href="https://www.google.com/maps/search/?api=1&query=Астана+Александра+Храпатого+21" target="_blank" rel="noopener noreferrer"><MapPin/><div><span>{t('Наш офис','Біздің кеңсе')}</span><strong>{t('Астана, ул. А. Храпатого, 21','Астана, А. Храпатый көшесі, 21')}</strong><p>{t('офис 41','41-кеңсе')}</p></div><ArrowUpRight/></a></div></div><div className="contact-panel"><MessageCircle/><h2>{t('Какой сервис нужен вашему объекту?','Нысаныңызға қандай сервис қажет?')}</h2><p>{t('Напишите в WhatsApp: тип объекта, его площадь и задачи. Это поможет нам предложить подходящий состав услуг.','WhatsApp арқылы нысан түрін, ауданын және міндеттерді жазыңыз. Бұл сізге қолайлы қызметтерді ұсынуға көмектеседі.')}</p><ul>{[t('Профессиональная уборка','Кәсіби тазалау'),t('Инженерное сопровождение','Инженерлік қолдау'),t('Комплексное обслуживание','Кешенді қызмет көрсету')].map(s=><li key={s}><Check/>{s}</li>)}</ul><RequestButton label={t('Написать в WhatsApp','WhatsApp арқылы жазу')}/><a href="mailto:info@aaaservice.kz" className="contact-email">{t('Или отправьте запрос на почту','Немесе поштаға сұрау жіберіңіз')}<ArrowRight size={16}/></a></div></section>;}

  return <div className={`site-frame page-${page}`} data-page={page}>
    <a href="#main" className="skip-link">{t('К содержанию','Мазмұнға өту')}</a>
    <header className="site-header"><div className="container header-inner"><a className="wordmark" href={path('home')} aria-label={t('AAA service — главная','AAA service — басты бет')}>AAA <span>service</span></a><nav className="desktop-nav" aria-label={t('Главное меню','Негізгі мәзір')}>{nav.map(n=>n.id==='services'?<div className={`nav-dropdown ${page===n.id?'current':''}`} key={n.id}><a href={path(n.id)} aria-current={page===n.id?'page':undefined}>{n.name}</a><details><summary aria-label={t('Направления услуг','Қызмет бағыттары')}><ChevronDown size={14}/></summary><div className="dropdown-panel">{detailGroups.map(g=><a key={g.id} href={`${path('services')}#${g.id}`} onClick={e=>{setServiceTab(g.id);e.currentTarget.closest('details')?.removeAttribute('open');}}>{g.title}<ArrowRight size={15}/></a>)}</div></details></div>:<a key={n.id} className={page===n.id?'current':''} href={path(n.id)} aria-current={page===n.id?'page':undefined}>{n.name}</a>)}</nav><div className="header-right"><div className="language-switch" aria-label={t('Язык сайта','Сайт тілі')}><a href={page==='home'?'/':`/${page}`} className={locale==='ru'?'active':''} hrefLang="ru" aria-current={locale==='ru'?'true':undefined}>RU</a><span/><a href={`/kz${page==='home'?'':`/${page}`}`} className={locale==='kz'?'active':''} hrefLang="kk" aria-current={locale==='kz'?'true':undefined}>KZ</a></div><div className="header-cta"><RequestButton label={page==='cases'?t('Обсудить объект','Нысанды талқылау'):undefined}/></div><Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetTrigger asChild><button className="mobile-menu-toggle" aria-label={t('Открыть меню','Мәзірді ашу')}><Menu/></button></SheetTrigger><SheetContent className="mobile-sheet" showCloseButton={false}><div className="mobile-sheet-top"><SheetTitle className="wordmark">AAA <span>service</span></SheetTitle><SheetClose className="mobile-close" aria-label={t('Закрыть меню','Мәзірді жабу')}><X/></SheetClose></div><SheetDescription className="sr-only">{t('Навигация по сайту AAA service','AAA service сайтындағы навигация')}</SheetDescription><nav aria-label={t('Мобильное меню','Мобильді мәзір')}>{nav.map(n=><div key={n.id}><a onClick={()=>setMenuOpen(false)} href={path(n.id)} className={page===n.id?'current':''}>{n.name}<ArrowRight size={20}/></a>{n.id==='services'&&<details className="mobile-services"><summary>{t('Направления услуг','Қызмет бағыттары')}<ChevronDown size={18}/></summary>{detailGroups.map(g=><a key={g.id} href={`${path('services')}#${g.id}`} onClick={()=>{setMenuOpen(false);setServiceTab(g.id);}}>{g.title}</a>)}</details>}</div>)}</nav><div className="mobile-contact"><RequestButton label={t('Обсудить объект','Нысанды талқылау')}/><a href="tel:+77012200112">+7 701 220 01 12</a></div></SheetContent></Sheet></div></div></header>
    <main id="main">{Hero()}{page==='home'&&HomeContent()}{page==='about'&&AboutContent()}{page==='services'&&ServicesContent()}{page==='cases'&&CasesContent()}{page==='contacts'&&ContactsContent()}<div className="container banner-container"><Banner red={page==='cases'}/></div></main>
    <footer className="site-footer container"><div className="footer-main"><a href={path('home')} className="wordmark">AAA <span>service</span></a><nav aria-label={t('Меню внизу страницы','Бет соңындағы мәзір')}>{nav.map(n=><a key={n.id} href={path(n.id)}>{n.name}</a>)}</nav><a href="tel:+77012200112"><Phone size={16}/>+7 701 220 01 12</a><a href="mailto:info@aaaservice.kz"><Mail size={16}/>info@aaaservice.kz</a></div><div className="footer-bottom"><p>© 2026 AAA service. {t('Все права защищены.','Барлық құқықтар қорғалған.')}</p><span><MapPin size={14}/>{t('Астана, ул. А. Храпатого, 21, офис 41','Астана, А. Храпатый көшесі, 21, 41-кеңсе')}</span>{page!=='home'&&<a href={path('home')} className="back-home"><ArrowLeft size={14}/>{t('На главную','Басты бетке')}</a>}</div></footer>
    <Dialog open={selectedCase!==null} onOpenChange={open=>{if(!open)setSelectedCase(null);}}><DialogContent className="case-dialog">{selectedCase!==null&&<><Photo name={cases[selectedCase].photo}/><Eyebrow>{cases[selectedCase].label}</Eyebrow><DialogTitle>{cases[selectedCase].name}</DialogTitle><DialogDescription>{cases[selectedCase].details}</DialogDescription><div className="dialog-date"><CalendarDays size={18}/>{cases[selectedCase].date}<span>·</span>{cases[selectedCase].city}</div><RequestButton label={t('Обсудить похожий объект','Ұқсас нысанды талқылау')}/></>}</DialogContent></Dialog>
  </div>;
}
